version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  seedmelab:
    build:
      context: seedmelab
    container_name: seedmelab
    restart: always
    ports:
    - "8080:80"
    volumes:
      - seedmelab_private_files:/var/private/
      - seedmelab_www:/var/www/
    environment:
      APACHE_DOCUMENT_ROOT: "/var/www/web"
    depends_on:
      - db

  volume_utility:
    build:
      context: volume_utility
    container_name: volume_utility
    volumes:
      - seedmelab_private_files:/volumes/seedmelab_private_files/
      - seedmelab_www:/volumes/seedmelab_www/
      - db_data:/volumes/db_data/
      - ${PWD}/backup:/backup/

volumes:
  db_data:
  seedmelab_private_files:
  seedmelab_www: