version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  seedmelab:
    build:
      context: seedmelab
    container_name: seedmelab
    restart: always
    ports:
    - "8080:80"
    volumes:
      - www_vol:/var/www/
      - seedmelab_private_files:/var/private/
#      - seedmelab_modules:/var/www/web/modules/
#      - seedmelab_themes:/var/www/web/themes/
    environment:
      APACHE_DOCUMENT_ROOT: "/var/www/web"
    depends_on:
      - db

  nginx-proxy:
    network_mode: bridge
    build: ./nginx_proxy/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    depends_on:
      - seedmelab
      - nginx-letsencrypt

  nginx-letsencrypt:
    network_mode: bridge
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    environment:
      LETSENCRYPT_KEYSIZE: 2048

volumes:
  certs:
  html:
  vhost:
  dhparam:
  db_data:
  www_vol:
  seedmelab_private_files:

#  seedmelab_modules:
#  seedmelab_themes:
